### PR TITLE
Deprecate kubelet-registration-probe

### LINKED ISSUE #309: Deprecate `--mode` option `kubelet-registration-probe`
In https://github.com/kubernetes-csi/node-driver-registrar/issues/143 we added a workaround for a race condition happening in Windows only in the kubelet registration mechanism, as part of the workaround I added the flag mode in https://github.com/kubernetes-csi/node-driver-registrar/pull/152 which through a livenessProbe would crash the Pod if the kubelet registration failed, fortunately @luckerby found the race in https://github.com/kubernetes/kubernetes/issues/104584#issuecomment-1108492823 and fixed it upstream.

With the above fix the `mode` flag is no longer needed and can be deprecated, its introduction created issues with the probe file it created in readOnly filesystems as seen in https://github.com/kubernetes-csi/node-driver-registrar/issues/244.

I still need to define the deprecation timeline and the steps to remove the flag.

```[tasklist]
### Tasks
- [ ] Remove code that creates the probe
- [ ] Update the docs removing references of this flag
```

As an alternative we can keep the feature but under the hood we would do nothing when `--mode=kubelet-registration-probe`, if so then I can safely remove the code that tries to create a file.

### PR DESCRIPTION
**Pull request by mattcary**
This also removes an unnecessary write to the root filesystem which prevents this driver as running under a readOnlyRootFilesystem security context

Fixes #309, #315

/assign @mauriciopoppe 

/kind cleanup

```release-note
Deprecate kubelet-registration-probe and remove unnecessary write to root filesystem.
```

### CODE REVIEW

File: cmd/csi-node-driver-registrar/main.go [hunk 1]
```diff
@@ -69,7 +60,7 @@ var (
...
 	httpEndpoint            = flag.String("http-endpoint", "", "The TCP network address where the HTTP server for diagnostics, including pprof and the health check indicating whether the registration socket exists, will listen (example: `:8080`). The default is empty string, which means the server is disabled. Only one of `--health-port` and `--http-endpoint` can be set.")
 	showVersion             = flag.Bool("version", false, "Show version.")
-	mode                    = flag.String("mode", ModeRegistration, `The running mode of node-driver-registrar. "registration" runs node-driver-registrar as a long running process. "kubelet-registration-probe" runs as a health check and returns a status code of 0 if the driver was registered successfully, in the probe definition make sure that the value of --kubelet-registration-path is the same as in the container.`)
+	mode                    = flag.String("mode", ModeRegistration, "DEPRECATED. This flag is no longer used. If this is set to kubelet-registration-probe, the driver will immediately exist successfully without registering with CSI.")
```
Comment (mauriciopoppe) [inline cmd/csi-node-driver-registrar/main.go:63]:
```suggestion
	mode                    = flag.String("mode", ModeRegistration, "DEPRECATED. This flag is no longer used. If this is set to kubelet-registration-probe, the driver will immediately exit successfully without registering with CSI.")
```

File: cmd/csi-node-driver-registrar/main.go [hunk 2]
```diff
@@ -101,14 +92,6 @@ func newRegistrationServer(driverName string, endpoint string, versions []string
 func (e registrationServer) GetInfo(ctx context.Context, req *registerapi.InfoRequest) (*registerapi.PluginInfo, error) {
 	klog.Infof("Received GetInfo call: %+v", req)
 
-	// on successful registration, create the registration probe file
-	err := util.TouchFile(registrationProbePath)
```
Comment (mauriciopoppe) [inline cmd/csi-node-driver-registrar/main.go:105]: There's test code for this function that we can remove

File: cmd/csi-node-driver-registrar/main.go [hunk 3]
```diff
@@ -145,22 +128,10 @@ func main() {
 		klog.Error("kubelet-registration-path is a required parameter")
 		os.Exit(1)
 	}
-	// set after we made sure that *kubeletRegistrationPath exists
-	kubeletRegistrationPathDir := filepath.Dir(*kubeletRegistrationPath)
-	registrationProbePath = filepath.Join(kubeletRegistrationPathDir, "registration")
 
-	// with the mode kubelet-registration-probe
 	if modeIsKubeletRegistrationProbe() {
-		lockfileExists, err := util.DoesFileExist(registrationProbePath)
```
Comment (mauriciopoppe) [inline cmd/csi-node-driver-registrar/main.go:154]: I forgot if I added this function or if it was already there, there's test code for it that might be dead code too

**Review by mauriciopoppe — COMMENTED** [review]
Thanks for the help removing the code, could you also update README.md please?

File: cmd/csi-node-driver-registrar/main.go (hunk 1 above)
Comment (mattcary) [reply cmd/csi-node-driver-registrar/main.go:63]: Well, it will immediately exist too... :-P

File: cmd/csi-node-driver-registrar/main.go (hunk 2 above)
Comment (mattcary) [reply cmd/csi-node-driver-registrar/main.go:105]: Oops I didn't even think about tests, thx.

File: cmd/csi-node-driver-registrar/main.go (hunk 3 above)
Comment (mattcary) [reply cmd/csi-node-driver-registrar/main.go:154]: +1

**Comment by mattcary** [comment]
Thanks for the review, I'll update the README which I also overlooked.

File: cmd/csi-node-driver-registrar/main.go (hunk 3 above)
Comment (mattcary) [reply cmd/csi-node-driver-registrar/main.go:154]: Yup it seems to be dead.

**Comment by mauriciopoppe** [comment]
hey @mattcary, friendly ping about the node-driver-registrar change about the kubelet-registration-probe

**Comment by mattcary** [comment]
Sorry for the delay. Done.
