### PR TITLE
Remove registratation socket file on shutdown

### LINKED ISSUE #21: remove reg.sock on shutdown
When driver-registrar terminates, it should ensure that it removes the `*-reg.socket` file that it created. It will get overwritten when restarting, but when experimenting with different drivers or testing with driver renaming, those files accumulate under `/var/lib/kubelet/plugins/` and then plugin registration in kubelet gets slower (several minutes!). That might be something worth fixing in kubelet (not sure?), but either way it is better to clean up.

Not much can be done when the registrar gets killed with SIGKILL or crashes, but hopefully that'll be rare.

This is something I've seen with driver-registrar 0.4.1, but probably still applies.

### PR DESCRIPTION
**Pull request by Madhu-1**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

when terminating, remove the *-reg.socket file created by node-driver-registrar

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #21

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by verult** [comment]
There's also work to make the registrar reconcile socket if it doesn't exist when it should: https://github.com/kubernetes-csi/node-driver-registrar/pull/60

**Comment by Madhu-1** [comment]
@msau42 CI passed PTAL

**Comment by Madhu-1** [comment]
@msau42 can you please review this PR?

**Comment by msau42** [comment]
/assign @verult 
I will defer review to @verult, who is also reviewing #60, which may conflict a little with this

**Comment by Madhu-1** [comment]
@verult can you please review this one.

File: cmd/csi-node-driver-registrar/node_register.go [hunk 1]
```diff
@@ -20,22 +20,28 @@ import (
...
+
 func nodeRegister(
 	csiDriverName string,
 ) {
 	// When kubeletRegistrationPath is specified then driver-registrar ONLY acts
 	// as gRPC server which replies to registration requests initiated by kubelet's
 	// pluginswatcher infrastructure. Node labeling is done by kubelet's csi code.
 	registrar := newRegistrationServer(csiDriverName, *kubeletRegistrationPath, supportedVersions)
-	socketPath := fmt.Sprintf("/registration/%s-reg.sock", csiDriverName)
+	socketPath := fmt.Sprintf("%s/%s-reg.sock", sockerDirPath, csiDriverName)
```
Comment (verult) [inline cmd/csi-node-driver-registrar/node_register.go]: nit: Could you pull this into a function like `buildSocketPath(csiDriverName)`? Right now, part of the socket path is pulled out as a const but part of it isn't

File: cmd/csi-node-driver-registrar/node_register.go [hunk 2]
```diff
@@ -77,3 +84,16 @@ func nodeRegister(
...
 	os.Exit(0)
 }
+
+func removeRegSocket(csiDriverName string) {
+	sigc := make(chan os.Signal, 1)
+	signal.Notify(sigc, syscall.SIGTERM)
+	<-sigc
+	socketPath := fmt.Sprintf("%s/%s-reg.sock", sockerDirPath, csiDriverName)
+	err := os.Remove(socketPath)
+	if err != nil && os.IsNotExist(err) {
```
Comment (verult) [inline cmd/csi-node-driver-registrar/node_register.go]: Do you mean `!os.IsNotExists()`?

Comment (Madhu-1) [reply cmd/csi-node-driver-registrar/node_register.go]: correct. fixed now

File: cmd/csi-node-driver-registrar/node_register.go (hunk 1 above)
Comment (Madhu-1) [reply cmd/csi-node-driver-registrar/node_register.go]: updated now

**Comment by Madhu-1** [comment]
> Sorry for the delay and thanks for the PR! Mostly LGTM.
> 
> How did you test this change?

deleted the nodeplugin daemonset which has the node-registrar container, verified the socket present on the node or not, it was deleted

**Comment by Madhu-1** [comment]
@verult PTAL

File: cmd/csi-node-driver-registrar/node_register.go [hunk 3]
```diff
@@ -77,3 +80,20 @@ func nodeRegister(
...
+func buildSocketPath(csiDriverName string) string {
+	return fmt.Sprintf("/registration/%s-reg.sock", csiDriverName)
+}
+
+func removeRegSocket(csiDriverName string) {
+	sigc := make(chan os.Signal, 1)
+	signal.Notify(sigc, syscall.SIGTERM)
+	<-sigc
+	socketPath := buildSocketPath(csiDriverName)
+	err := os.Remove(socketPath)
```
Comment (kkmsft) [inline cmd/csi-node-driver-registrar/node_register.go]: In the main code path we remove it only if it's a socket (not sure why). Can you please clarify why we are removing in this path without doing the same check ? I think we should have a single code path for delete which is called from the sync path and from the async signal path as well.

File: cmd/csi-node-driver-registrar/node_register.go [hunk 4]
```diff
@@ -77,3 +80,20 @@ func nodeRegister(
...
 	os.Exit(0)
 }
+
+func buildSocketPath(csiDriverName string) string {
+	return fmt.Sprintf("/registration/%s-reg.sock", csiDriverName)
+}
+
+func removeRegSocket(csiDriverName string) {
+	sigc := make(chan os.Signal, 1)
+	signal.Notify(sigc, syscall.SIGTERM)
```
Comment (kkmsft) [inline cmd/csi-node-driver-registrar/node_register.go]: Any ideas whether this will work on windows ? @ddebroy - any ideas ?
If not can you please move this to linux utils ?

File: cmd/csi-node-driver-registrar/node_register.go (hunk 3 above)
Comment (Madhu-1) [reply cmd/csi-node-driver-registrar/node_register.go]: the check is not required here, only we are going to delete the socket if it is not present we are discarding the error, we are good here

File: cmd/csi-node-driver-registrar/node_register.go (hunk 4 above)
Comment (Madhu-1) [reply cmd/csi-node-driver-registrar/node_register.go]: if someone confirms it wont work in windows i will move it linunx_utils

Comment (verult) [reply cmd/csi-node-driver-registrar/node_register.go]: cc @jingxu97 as well

File: cmd/csi-node-driver-registrar/node_register.go (hunk 3 above)
Comment (verult) [reply cmd/csi-node-driver-registrar/node_register.go]: The original check seems wrong (if the file isn't a socket, proceed and listen to it anyway...?) It should be fixed but doesn't have to be in this PR

I agree we don't need the check here - the socket should've been created by a node-driver-registrar and if something dropped a different file in its place, it did so at its own risk

**Comment by Madhu-1** [comment]
resolved merge conflict and rebased. @msau42 can you please review this one, we had a approval from @verult after rebasing bot removed it.

**Comment by msau42** [comment]
/assign @ddebroy @jingxu97 
to review Windows aspect

**Comment by Madhu-1** [comment]
@msau42 @ddebroy @jingxu97 can we get a review on this one?

File: cmd/csi-node-driver-registrar/node_register.go (hunk 4 above)
Comment (ddebroy) [reply cmd/csi-node-driver-registrar/node_register.go:83]: Notifications on `syscall.SIGTERM` does work for Windows: https://golang.org/pkg/os/signal/#hdr-Windows. So LGTM from a Windows perspective. cc @jingxu97

**Comment by ddebroy** [comment]
Commented about the Windows sigterm notification at https://github.com/kubernetes-csi/node-driver-registrar/pull/61/files#r463444043 . @jingxu97 if you can confirm the GCE PD Windows driver is able to clean up the scoket  file properly then this will be good 2 merge.
